import crypto from "crypto";
import { env } from "../env";
export interface TiktokAppCredentials { appKey: string; appSecret: string }
function sign(creds:TiktokAppCredentials,path:string,params:Record<string,string>,rawBody:string):string { const keys=Object.keys(params).filter(k=>k!=="sign"&&k!=="access_token").sort(); let base=path; for(const k of keys) base+=k+params[k]; base+=rawBody; const wrapped=creds.appSecret+base+creds.appSecret; return crypto.createHmac("sha256",creds.appSecret).update(wrapped).digest("hex"); }
function nowTs(){return Math.floor(Date.now()/1000)}
export interface TiktokTokenResponse { access_token:string; refresh_token:string; access_token_expire_in:number; refresh_token_expire_in:number; open_id?:string; seller_name?:string; code?:number; message?:string }
export function buildAuthUrl(creds:TiktokAppCredentials,state:string):string { const url=new URL(`${env.tiktokAuthHost()}/oauth/authorize`); url.searchParams.set("app_key",creds.appKey); url.searchParams.set("state",state); return url.toString(); }
export async function exchangeCodeForToken(creds:TiktokAppCredentials,code:string):Promise<TiktokTokenResponse>{ const url=new URL(`${env.tiktokAuthHost()}/api/v2/token/get`); url.searchParams.set("app_key",creds.appKey); url.searchParams.set("app_secret",creds.appSecret); url.searchParams.set("auth_code",code); url.searchParams.set("grant_type","authorized_code"); const res=await fetch(url.toString()); return (await res.json()) as TiktokTokenResponse; }
export async function refreshAccessToken(creds:TiktokAppCredentials,refreshToken:string):Promise<TiktokTokenResponse>{ const url=new URL(`${env.tiktokAuthHost()}/api/v2/token/refresh`); url.searchParams.set("app_key",creds.appKey); url.searchParams.set("app_secret",creds.appSecret); url.searchParams.set("refresh_token",refreshToken); url.searchParams.set("grant_type","refresh_token"); const res=await fetch(url.toString()); return (await res.json()) as TiktokTokenResponse; }
export async function getAuthorizedShops(creds:TiktokAppCredentials,accessToken:string){ const path="/authorization/202309/shops"; const params={app_key:creds.appKey,timestamp:String(nowTs())}; const signature=sign(creds,path,params,""); const url=new URL(env.tiktokApiHost()+path); for(const [k,v] of Object.entries(params)) url.searchParams.set(k,v); url.searchParams.set("sign",signature); const res=await fetch(url.toString(),{headers:{"x-tts-access-token":accessToken}}); return res.json(); }
async function signedCall<T=any>(creds:TiktokAppCredentials,path:string,accessToken:string,shopId:string,shopCipher:string,method:"GET"|"POST",query:Record<string,string>={},body?:Record<string,any>):Promise<T>{ const params:Record<string,string>={app_key:creds.appKey,shop_id:shopId,shop_cipher:shopCipher,timestamp:String(nowTs()),...query}; const rawBody=body?JSON.stringify(body):""; const signature=sign(creds,path,params,rawBody); const url=new URL(env.tiktokApiHost()+path); for(const [k,v] of Object.entries(params)) url.searchParams.set(k,v); url.searchParams.set("sign",signature); const res=await fetch(url.toString(),{method,headers:{"x-tts-access-token":accessToken,"Content-Type":"application/json"},body:method==="POST"?rawBody:undefined}); return (await res.json()) as T; }
export const searchOrders=(c:TiktokAppCredentials,t:string,s:string,sc:string,p:{createTimeFrom:number;createTimeTo:number;pageSize?:number;pageToken?:string})=>signedCall(c,"/order/202309/orders/search",t,s,sc,"POST",{page_size:String(p.pageSize??50),...(p.pageToken?{page_token:p.pageToken}:{})},{create_time_ge:p.createTimeFrom,create_time_lt:p.createTimeTo});
export const getOrderDetail=(c:TiktokAppCredentials,t:string,s:string,sc:string,ids:string[])=>signedCall(c,"/order/202309/orders",t,s,sc,"GET",{ids:JSON.stringify(ids)});
export const searchProducts=(c:TiktokAppCredentials,t:string,s:string,sc:string,p:{pageSize?:number;pageToken?:string})=>signedCall(c,"/product/202309/products/search",t,s,sc,"POST",{page_size:String(p.pageSize??50),...(p.pageToken?{page_token:p.pageToken}:{})},{});
